
name: 'Workload-Identity'

on:
  push:
    branches: [ "main" ]

jobs:
  wif-tes:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    defaults:
      run:
        shell: bash

    steps:
    - name: checkout
      uses: actions/checkout@v3


    - name: Auth GCP
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/${{secrets.PROJECT_NUMBER}}/locations/global/workloadIdentityPools/${{secrets.POOL_NAME}}/providers/${{secrets.PROVIDERS_NAME}}'
        service_account: ${{secrets.SERVICE_ACCOUNT}}
        token_format: "access_token"
        create_credentials_file: true
        activate_credentials_file: true
    
    # - name: tf apply
    #   run: |- 
    #     cd resources
    #     terraform init
    #     terraform plan -input=false
    #     terraform apply -auto-approve -input=false

    - name: tf destroy
      run: |- 
        cd resources
        terraform init
        terraform destroy -auto-approve -input=false
